### ISSUE TITLE
很棒的代码，为什么不做一个针对AI绘画的open pose编辑器。

### ISSUE THREAD

**Issue by ZhUyU1997** [KonghaYao/poser#1]

**Comment by KonghaYao** [comment]
感谢您的关注，本来是想要做的，但是这个项目其实是一个网站源码中复现出来的，里面的默认姿势都是那个项目的作品，我只是借来测试了一下，发现这个确实可以承担的骨骼绘制功能。
没有继续做的原因是 1. 改那个项目的代码太累了，js 转 ts ，并且很多类型没有声明完全，只是做到能够使用的地步😂。2. 图生图的原理是根据像素颜色分辨的，所以对姿势。。。emmm。当然现在有个技术支持姿势生成，已经可以集成在 SD 里面，也挺不错了。3. 我并没有想像力去扩展这个项目，因为最近在重构中华诗词大典，那个项目巨大且耗费精力太大了😂。
总之，有计划还是会把它继承到 魔导绪论 里面的。😄
